const state={
        navSW:[
            {id:1,headerLink:'BOOKS',parts:[
                {id:1,name:'AI',router:'/imageview/'},
                {id:2,name:'Developer',router:'/imageview/developer'},
                {id:3,name:'Software Engineer',router:'/imageview/softwareengineer'},
            ]},
        ],
        popoverBook:[
            {id:1,href:"ai01",title:"algorithm",dataContent:'some content inside the popover',text:'lesson one',content:"Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar."},
            {id:2,href:"ai02",title:"AI02",dataContent:'some content inside the popover',text:'lesson two',content:"Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar."},
            {id:3,href:"ai03",title:"AI03",dataContent:'some content inside the popover',text:'lesson two',content:"Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar."},
            {id:4,href:"ai04",title:"AI04",dataContent:'some content inside the popover',text:'lesson three',content:"Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar."},
            {id:5,href:"ai05",title:"AI05",dataContent:'some content inside the popover',text:'lesson four',content:"Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar."},
            {id:6,href:"ai06",title:"AI06",dataContent:'some content inside the popover',text:'lesson five',content:"Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar."},
            {id:7,href:"ai07",title:"AI07",dataContent:'some content inside the popover',text:'lesson six',content:"Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar."},
            {id:8,href:"ai08",title:"AI07",dataContent:'some content inside the popover',text:'lesson seven',content:"Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar."},
            {id:9,href:"ai09",title:"AI09",dataContent:'some content inside the popover',text:'lesson eight',content:"Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar."},
            {id:10,href:"ai10",title:"AI10",dataContent:'some content inside the popover',text:'lesson nine',content:"Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar."},
            {id:11,href:"ai11",title:"AI11",dataContent:'some content inside the popover',text:'lesson eleven',content:"Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar."},
            {id:12,href:"ai12",title:"AI12",dataContent:'some content inside the popover',text:'lesson twelve',content:"Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar."},
            {id:13,href:"ai13",title:"AI13",dataContent:'some content inside the popover',text:'lesson thirteen',content:"Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar."},
            {id:14,href:"ai14",title:"AI14",dataContent:'some content inside the popover',text:'lesson fourteen',content:"Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar."},
            {id:15,href:"ai15",title:"AI15",dataContent:'some content inside the popover',text:'lesson fiveteen',content:"Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar."},
            {id:16,href:"ai16",title:"AI16",dataContent:'some content inside the popover',text:'lesson sixteen',content:"Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar."},
            {id:17,href:"ai17",title:"AI17",dataContent:'some content inside the popover',text:'lesson seveteen',content:"Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar."},
            {id:18,href:"ai18",title:"AI18",dataContent:'some content inside the popover',text:'lesson eightteen',content:"Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar."},
            {id:19,href:"ai19",title:"AI19",dataContent:'some content inside the popover',text:'lesson nineteen',content:"Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar."},
            {id:20,href:"ai20",title:"AI20",dataContent:'some content inside the popover',text:'lesson twenty',content:"Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document. To make your document look professionally produced, Word provides header, footer, cover page, and text box designs that complement each other. For example, you can add a matching cover page, header, and sidebar."},
         
        ]
        
};
const getters={};

const mutations={}

const actions={};

export default {
    state,
    getters,
    mutations,
    actions
}